# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: test_debug

on:
  push:
    branches: [ master, citest, cidebug ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java, R and UTF8
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get install -yq locales tzdata
        sudo locale-gen "en_US.UTF-8"
        sudo bash -c 'echo "LANG=en_US.UTF-8" > /etc/default/locale'
        sudo apt-get install -yq openjdk-8-jdk-headless maven
        sudo apt-get install -yq r-base
    - name: test UTF-8 in R
      run: printf "s = intToUtf8(500:550) \n s" | R --vanilla
    - name: Build with Maven
      run: cd RCaller && mvn test
